pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
#    when:
#      event: pull_request
    mount:
      - .gradle
      - gradle_cache
#      - build
    volumes:
      - /cache:/cache/

  commits:
      image: plugins/git
      commands:
        - echo 'start'
        - echo ${DRONE_COMMIT_LINK:57}
        - git log ${DRONE_COMMIT_LINK:57} --pretty=format:"%h - %an %ad - %s " --date=format:'%Y-%m-%d' >changelog.txt
        - cat changelog.txt

  build:
    image: androidci
    secrets: 
      - DEBUG
      - LICENA
      - LICENB
    volumes:
      - /cache:/cache/
      - /data/gradle/gradle-4.7:/gradle/
    when:
      branch: dev_student
      event: push
    commands:
      - agree-license.sh android-sdk-license $LICENA
      - agree-license.sh android-sdk-preview-license $LICENB
      - echo 'start'
      - /gradle/bin/gradle -g gradle_cache :staff:assembleDevDebug --no-daemon
      - fir publish staff/build/outputs/apk/dev/debug/staff-dev-debug.apk -T $DEBUG -c changelog.txt
#      - fir publish trainer/build/outputs/apk/trainer-dev-debug.apk -T $DEBUG
  mirror:
    image: androidci
    secrets: 
      - PRO
      - LICENA
      - LICENB
    when:
      branch: develop
    volumes:
      - /cache:/cache/
      - /data/gradle/gradle-4.7:/gradle/
    commands:
      - agree-license.sh android-sdk-license $LICENA
      - agree-license.sh android-sdk-preview-license $LICENB
      - echo 'start'
      - ./gradlew -g gradle_cache assembleProductRelease --no-daemon
#      - fir publish staff/build/outputs/apk/product/release/staff-product-release.apk -T $PRO
#      - fir publish trainer/build/outputs/apk/trainer-product-release.apk -T $PRO

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    #    when:
    #      event: pull_request
    mount:
      - .gradle
      - gradle_cache
#      - build
    volumes:
      - /cache:/cache/
  wechat:
      image: lizheming/drone-wechat
      sckey: SCU20429Tda835b752e6cc08e10d276d233ca8b5f5a61ea96a6847
      title: 青橙健身管理有更新
      message: >
        {%if success %}
          build {{build.number}} 青橙健身管理成功上传到fir.im/staffbeta
        {% else %}
          build {{build.number}} 青橙健身管理编译失败
        {% endif %}
