pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - .gradle
      - gradle_cache
#      - build
    volumes:
      - /tmp/cache:/cache/
  build:
    image: androidci
    workspace:
      base: /root
    secrets: 
      - DEBUG
      - LICENA
      - LICENB
    when: 
      event: pull_request
    commands:
      - agree-license.sh android-sdk-license $LICENA
      - agree-license.sh android-sdk-preview-license $LICENB
      - echo 'start'
      - ./gradlew -g gradle_cache assembleDevDebug --no-daemon
      - fir publish staff/build/outputs/apk/staff-dev-debug.apk -T $DEBUG
      - fir publish trainer/build/outputs/apk/trainer-dev-debug.apk -T $DEBUG
  mirror:
    image: androidci
    workspace:
      base: /root
    secrets: 
      - PRO
      - LICENA
      - LICENB
    when: 
    when: 
      branch: develop
    commands:
      - agree-license.sh android-sdk-license $LICENA
      - agree-license.sh android-sdk-preview-license $LICENB
      - echo 'start'
      - ./gradlew -g gradle_cache assembleProductRelease --no-daemon
      - fir publish staff/build/outputs/apk/staff-product-release.apk -T $PRO
      - fir publish trainer/build/outputs/apk/trainer-product-release.apk -T $PRO
  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - .gradle
      - gradle_cache
#      - build
    volumes:
