pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - .gradle
      - gradle_cache
#      - build
    volumes:
      - /cache:/cache/



  build:
    image: androidci
    secrets: 
      - DEBUG
      - LICENA
      - LICENB
    volumes:
      - /cache:/cache/
#    when:
#      event: pull_request
    commands:
      - agree-license.sh android-sdk-license $LICENA
      - agree-license.sh android-sdk-preview-license $LICENB
      - echo 'start'
      - /cache/gradle/gradle-4.1/bin/gradle -g gradle_cache assembleDevDebug --no-daemon
      - fir publish staff/build/outputs/apk/dev/debug/staff-dev-debug.apk -T $DEBUG
#      - fir publish trainer/build/outputs/apk/trainer-dev-debug.apk -T $DEBUG
  mirror:
    image: androidci
    secrets: 
      - PRO
      - LICENA
      - LICENB
    when:
      branch: develop
    commands:
      - agree-license.sh android-sdk-license $LICENA
      - agree-license.sh android-sdk-preview-license $LICENB
      - echo 'start'
      - ./gradlew -g gradle_cache assembleProductRelease --no-daemon
      - fir publish staff/build/outputs/apk/product/release/staff-product-release.apk -T $PRO
#      - fir publish trainer/build/outputs/apk/trainer-product-release.apk -T $PRO

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    #    when:
    #      event: pull_request
    mount:
      - .gradle
      - gradle_cache
#      - build
    volumes:
