-keep class cn.qingchengfit.staffkit.App.{*;}
-keep class cn.qingchengfit.staffkit.inject.commpont.DaggerAppComponet
-keep class cn.qingchengfit.staffkit.inject.{*;}
-keep class cn.qingchengfit.staffkit.model.db.{*;}
-keep class rx.{*;}
